### ISSUE TITLE
Chinese layout not work

### ISSUE THREAD

**Issue by chenhailun2006** [simple-keyboard/simple-keyboard-layouts#1151]
**Simple-keyboard version**
As some bugs have been addressed in later versions, please ensure you are running the latest.

**Describe the bug**
Chinese layout not work, when I input something, there should have candidate words of chinese, but it doesn't

**Screenshots**
![image](https://user-images.githubusercontent.com/11553618/124750967-ae573900-df58-11eb-89f5-2ee552aa6e1c.png)

**Comment by hodgef** [comment]
Hey @chenhailun2006,

Here's the configuration for the Chinese layout:
https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/chinese.ts

Here's a demo:
https://codesandbox.io/s/github/hodgef/simple-keyboard-layouts-demos/tree/chinese/?from-embed

In this demo I'm able to type "ni" and get some suggestions. Is this not working for you or do you expect something different?

Thanks,
Francisco Hodge

**Comment by maxfahl** [comment]
This is related to what you said @hodgef.

The suggestions work fine with lower case letters, but do not work on upper case letters. Is this something you're aware of?

**Comment by hodgef** [comment]
Hey @maxfahl, this should now be fixed in:

simple-keyboard v3.3.21
react-simple-keyboard v3.3.30

Regards,
Francisco Hodge
