### ISSUE TITLE
Layout candidates not replacing text on shift mode

### ISSUE THREAD

**Issue by maxfahl** [simple-keyboard/simple-keyboard-layouts#1361]
Running 3.3.0, the candidates now show up when writing all capitalized characters (shift), so that is an improvement. But when testing this, I noticed that when clicking on a candidate in the box, the word I'm trying to replace will stay as it was before, no replacement is happening.

Thank you for your great work and fast responses @hodgef

**Comment by hodgef** [comment]
Hey @maxfahl,

Thanks for filing this. Sadly I didn't think of clicking the buttons! Will fix shortly

**Comment by maxfahl** [comment]
Easy to miss the details sometimes, thank you!

**Comment by hodgef** [comment]
The issue should be gone in these newly released versions:

simple-keyboard v3.3.22
react-simple-keyboard v3.3.31

Hopefully it works well this time! But if not please let me know.

Regards,
Francisco Hodge

**Comment by maxfahl** [comment]
Works like a charm. Thank you very much for your efforts!

**Comment by maxfahl** [comment]
Works like a charm. Thank you very much for your efforts!
