### ISSUE TITLE
Changing layout should also change function button text

### ISSUE THREAD

**Issue by xinthose** [simple-keyboard/simple-keyboard-layouts#1387]
If we change the keyboard layout to Spanish for example, shouldn't `backspace` change text to `retroceso`?  The same applies for all of the other keys.

I can accomplish this myself using the [`display`](https://hodgef.com//simple-keyboard/documentation/options/display/) option:

```
    display: {
        "{bksp}": this.spanishSelected ? "retroceso" : "backspace",
    },
```

**Comment by hodgef** [comment]
Hey @xinthose,

You're right, "backspace" should be translated as well. I initially intended translations to be directly added to the layout (as they are now), but this doesn't cover "function buttons" like `{bksp}`.

I thought of adding the `display` option to language layouts as you have done, but there's the concern of an existing option being overwritten. That might still be the best way however.

I will flag this as an enhancement as see if I can pick it up sometime soon.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Setting this back as proposal since it's going to take some refactoring to get this done. Thank you
