### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by christianstrang** [simple-keyboard/simple-keyboard-layouts#1477]
**Simple-keyboard version**
<pre>
"next": "^11.1.2",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-simple-keyboard": "^3.4.58",
"simple-keyboard-layouts": "^3.1.48"
</pre>

**Describe the bug**
The keyboard works fine with the english layout, but once I add layouts via "simple-keyboard-layouts", I receive "unexpected token export"; maybe an issue on my end with webpack?

**Code**
<pre>import Keyboard from 'react-simple-keyboard'  
import 'react-simple-keyboard/build/css/index.css'  
import german from 'simple-keyboard-layouts/build/layouts/german'</pre>

<pre>
  const [input, setInput] = useState('')
  const [layout, setLayout] = useState('default')
  const keyboard = useRef()

  const onChange = (input) => {
    setInput(input)
    console.log('Input changed', input)
  }

  const handleShift = () => {
    const newLayoutName = layout === 'default' ? 'shift' : 'default'
    setLayout(newLayoutName)
  }

  const onKeyPress = (button) => {
    console.log('Button pressed', button)

    /**
     * If you want to handle the shift and caps lock buttons
     */
    if (button === '{shift}' || button === '{lock}') handleShift()
  }

  const onChangeInput = (event) => {
    const input = event.target.value
    setInput(input)
    keyboard.current.setInput(input)
  }
</pre>

```
<div>
  <input
    className='block w-full rounded-md border border-[#ececec]  p-4 text-center text-lg shadow-sm focus:border-indigo-500 focus:ring-indigo-500'
    value={input}
    placeholder={'Tap on the virtual keyboard to start'}
    onChange={onChangeInput}
  />
  <Keyboard
    keyboardRef={(r) => (keyboard.current = r)}
    layoutName={layout}
    onChange={onChange}
    onKeyPress={onKeyPress}
    {...german}
  />
</div>
```

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/1850464/153719778-b4ad85ac-2ba1-495f-90fd-d4012a3a511e.png)

**Comment by hodgef** [comment]
Hey @christianstrang, indeed this appears to be an issue with your setup, do you mind sharing a test git repository (repro) so I can take a look? Otherwise you can get your layout like this:

```js
import KeyboardLayouts from 'simple-keyboard-layouts';
const german = new KeyboardLayouts().get("german");
```

However this method loads the full list of layouts, so it's preferred to go with the approach you went with.

I will reopen once I get a repro, thanks!
