### ISSUE TITLE
Backspace doesn't syncronize multiple keyboards 

### ISSUE THREAD

**Issue by sayands** [simple-keyboard/simple-keyboard-layouts#1626]
**Simple-keyboard version**
3.1.145

**Describe the bug**
I have 2 same language keyboards placed on the same screen. The steps to reproduce the issue  are : 

Type 123456 -> Place cursor after 3, 123|456 ( | symbol used to represent cursor) -> press backspace -> New text shown after deletion is '12345' instead of '12456' ( '6' gets deleted instead of '3' )

The issue seems similar to one in react-simple-keyboard repo as linked [here](https://github.com/hodgef/react-simple-keyboard/issues/1948)

**Screenshots**
Not applicable since a similar issue was raised in the aforementioned repo.

**Comment by hodgef** [comment]
I cannot repro this issue. Please re-file this in the simple-keyboard or react-simple-keyboard repository (depending on your use-case) and provide the full runnable example.
