### ISSUE TITLE
documentation about layout - (keyboard only)

### ISSUE THREAD

**Issue by c0ncentus** [simple-keyboard/simple-keyboard-layouts#1775]
**Is your feature request related to a problem? Please describe.**
i search deep into the doc but not solve a real basic issue, I feel kind a stupid.

**Describe the solution you'd like**
Make a TRUE "get started"  writting about parameters and type ...
it's take one paragraph not such hard work !

The rest of the doc is really good but research is like hell because open ~10 links and dont really have the behaviour specially desired.

**Describe alternatives you've considered**
either make it more exhaustive about layout page (all possibilities), either make an exemple with only keyboard because it is a large use case ... https://codesandbox.io/s/n5mllkkmyl?file=/src/index.js:2207-2291.
THAT link it is a good layout exemple (I think) !

**Additional context**
I'm new to the library and it's like very hight quality stuff !

**Comment by hodgef** [comment]
Hey @c0ncentus, the main repo for simple-keyboard is here: https://github.com/hodgef/simple-keyboard

I had made some adjustments so you can find the info quicker.

For example by bringing the "layout" docs to the top:
![image](https://user-images.githubusercontent.com/25509135/204073417-a2c124cd-60ef-4d34-9ccb-64e667d27dc2.png)
https://hodgef.com/simple-keyboard/documentation/options/layout/

And by having a questions and answers section to address common use cases:

![image](https://user-images.githubusercontent.com/25509135/204073454-53eff5c0-bcfb-4cc3-b5b0-442568aa7fa9.png)
https://hodgef.com/simple-keyboard/questions-answers/

I understand what you mean about having the params in one page, I will try to see how I can improve that in a future docs update. Thanks
