### ISSUE TITLE
Some layout file name does not match the content

### ISSUE THREAD

**Issue by pietrodicaprio** [simple-keyboard/simple-keyboard-layouts#1879]
**Simple-keyboard version**
main branch of repo

**Describe the bug**
The Norwegian layout is in truth Nigerian
The Turkish layout is in truth Swedish

**Screenshots**
Norwegian:
https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/norwegian.ts
~origin: https://github.com/bkmgit/simple-keyboard-layouts/commit/a9573aa4ceaa8b635e91d950d5596a290bfdbcfa~

Turkish:
https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/turkish.ts

**Comment by hodgef** [comment]
@pietrodicaprio Thanks for raising this issue. I think only the comments are wrong, but the layouts themselves are correct. Do you agree? I will correct the comments shortly.

**Comment by pietrodicaprio** [comment]
> @pietrodicaprio Thanks for raising this issue. I think only the attribution comments are wrong, but the layouts themselves are correct. Do you agree? I will correct the comments shortly.

I agree. Looks like I made a mistake in my checks yesterday! Sorry for that

**Comment by hodgef** [comment]
Fixed the comments, my mistake for mixing up the content there. Thanks a lot!
