### ISSUE TITLE
Add Option  / Alt Key and Support for Third Layout to Accommodate Languages That Need Third Layout

### ISSUE THREAD

**Issue by odunze** [simple-keyboard/simple-keyboard-layouts#1891]
The standard layout only supports two types: `default` and `shift` 

Some languages need more than the available space in two layouts, and could be supported by adding an Option / Alt key to access a third layout called `option` or `alt` (whichever you prefer) 

I would like to add a keyboard layout for an African writing system, but it requires a third layout as well.

Please consider it as many undocumented and unsupported languages (especially African languages) could stand to benefit from being able to add support to Simple Keyboard.

Example provided below: 

```
import { LayoutItem } from "../interfaces";

/**
 * Layout: Verbose Language
 */
export default <LayoutItem>{
  layout: {
    default: [
      "\u00B2 & \u00E9 \" ' ( - \u00E8 _ \u00E7 \u00E0 ) = {bksp}",
      "{tab} a z e r t y u i o p ^ $",
      "{lock} q s d f g h j k l m \u00F9 * {enter}",
      "{shift} < w x c v b n , ; : ! {shift}",
      ".com @ {space}",
    ],
    shift: [
      "{//} 1 2 3 4 5 6 7 8 9 0 \u00B0 + {bksp}",
      "{tab} A Z E R T Y U I O P \u00A8 \u00A3",
      "{lock} Q S D F G H J K L M % \u00B5 {enter}",
      "{shift} > W X C V B N ? . / \u00A7 {shift}",
      ".com @ {space}",
    ],
   option: [
      "{//} 1 2 3 4 5 6 7 8 9 0 \u00B0 + {bksp}",
      "{tab} A Z E R T Y U I O P \u00A8 \u00A3",
      "{lock} Q S D F G H J K L M % \u00B5 {enter}",
      "{shift} > W X C V B N ? . / \u00A7 {shift}",
      ".com @ {space}",
    ],
  },
};

```

**Comment by odunze** [comment]
@hodgef  Wondering whether this is addressed here by this demo which allows separate layouts for `caps` versus `shift` ?

https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-npm-demos/tree/uc-shiftandcaps

If so, in a language with no use for the `caps` function, (like I wish to add), would it be acceptable to submit a file with THREE layouts: `default` , `shift` and `caps` ?

**Comment by hodgef** [comment]
Hello @odunze,

I agree that this would be useful, however in all the demos the layouts are switched in the `onChange` and require for people to call `keyboard.setOptions..`. If a third layout were to be added, it would add some inconsistency and people would have to add extra code to handle this new layout.

For example: there are folks who have implemented a dropdown with all the languages. If a third layout were to be added, then their current implementation would be broken as the buttons that are supposed to trigger this new layout will do nothing.

There are ways to resolve this problem, but they would involve code changes in the library, and this is something that I would rather consider for a future release. I will track this as an Enhancement so I can follow up.

Regards,
Francisco Hodge
