### ISSUE TITLE
Missing variants for 4-letter syllables in Korean

### ISSUE THREAD

**Issue by dzikoysk** [simple-keyboard/simple-keyboard-layouts#1963]
I'll show the problem using `있` syllable, but I think several other variants may have the same issue:

`이ᄉ: "잇",` (3+1):

https://github.com/simple-keyboard/simple-keyboard-layouts/blob/6775b2402a0bcdfb3ba13772ba447f3d9686ab1a/src/lib/layouts/korean.ts#L7071

But `있` is constructed from `이ᄊ: "있"` (2+2):

https://github.com/simple-keyboard/simple-keyboard-layouts/blob/6775b2402a0bcdfb3ba13772ba447f3d9686ab1a/src/lib/layouts/korean.ts#L7072

Due to the lack of `ᄊ` (2), we're not able to construct `있` as it should be `잇ᄉ: "있"` for that case. I think that 4-letter syllables should have matching 3+1 variants, as any 2+2 won't be resolved by current impl.

**Comment by hodgef** [comment]
Same response as https://github.com/hodgef/simple-keyboard/issues/1994#issuecomment-1574342178

**Comment by dzikoysk** [comment]
Hmm, did you generate `korean.ts` using some kind of script? This file is pretty long and knowing that you're not familiar with Korean, I assume it was somehow automated.

**Comment by hodgef** [comment]
Unfortunately, I do not recall the sources (will link it as soon as I find it) but yes it was generated through script. Let's continue this conversation in https://github.com/hodgef/simple-keyboard/issues/1994#issuecomment-1574342178 as the CandidateBox logic is all done in the main library. Thanks!
