### ISSUE TITLE
Support for Khmer keyboard layout

### ISSUE THREAD

**Issue by dkc-1379** [simple-keyboard/simple-keyboard-layouts#2302]
Hi,
I'd like to see support for Khmer keyboard layout. I already have the implementation, but it's not like the  [(guide)](https://github.com/simple-keyboard/simple-keyboard-layouts/wiki/Adding-a-Layout) says to keep only two layouts, because Khmer has more letters. 
The Khmer layout will look like this:

        export const khmer= {
            default: [
              "« ១ ២ ៣ ៤ ៥ ៦ ៧ ៨ ៩ ០ គ ធ {bksp}",
              "{tab} ឆ ឹ េ រ ត យ ុ ិ ោ ផ ៀ ឨ ឮ",
              "{lock} ា ស ដ ថ ង ហ ្ ក ល ើ ់ {enter}",
              "{shift} \\ ឋ ខ ច វ ប ន ម ំុ ។ ៊ {shift}",
              ".com @ {space}",
            ],
            lock: [
              "« ១ ២ ៣ ៤ ៥ ៦ ៧ ៨ ៩ ០ គ ធ {bksp}",
              "{tab} ឈ ឺ ែ ឬ ទ ួ ូ ី ៅ ភ ៀ ឨ ឮ",
              "{lock} ាំ ៃ ឌ ធ ឣ ះ ញ គ ឡ ើ ់ {enter}",
              "{shift} \\ ឍ ឃ ជ េះ ព ណ ំ ំុ ។ ៊ {shift}",
              ".com @ {space}",
            ],
            shift: [
              "» ! ៗ \" ៛ % ៌ ័ ៏ ( ) ៝ ឪ {bksp}",
              "{tab} ឈ ឺ ែ ឬ ទ ួ ូ ី ៅ ភ ឿ ឧ ឭ",
              "{lock} ាំ ៃ ឌ ធ ឣ ះ ញ គ ឡ ោៈ ៉ {enter}",
              "{shift} / ឍ ឃ ជ េះ ព ណ ំ ុះ ៕ ? {shift}",
              ".com @ {space}",
            ],
            'shift-lock': [
              "» ! ៗ \" ៛ % ៌ ័ ៏ ( ) ៝ ឪ {bksp}",
              "{tab} ឆ ឹ េ រ ត យ ុ ិ ោ ផ ឿ ឧ ឭ",
              "{lock} ា ស ដ ថ ង ហ ្ ក ល ោៈ ៉ {enter}",
              "{shift} / ឋ ខ ច វ ប ន ម ុះ ៕ ? {shift}",
              ".com @ {space}",
            ],
          }

Its handleShiftButton function will look like this:

      handleShiftButton = (button: string) => {
        const list = this.layoutName.split('-')
        switch (button) {
          case '{lock}':
            if (this.layoutName === 'default') {
              list.splice(0, 1, 'lock')
            } else if (this.layoutName === 'lock') {
              list.splice(0, 1, 'default')
            } else if (this.layoutName === 'shift') {
              list.push('lock')
            } else {
              list.pop()
            }
            break
          case '{shift}':
            if (this.layoutName === 'default') {
              list.splice(0, 1, 'shift')
            } else if (this.layoutName === 'shift') {
              list.splice(0, 1, 'default')
            } else if (this.layoutName === 'lock') {
              list.unshift('shift')
            } else {
              list.shift()
            }
            break
        }
        this.keyboard.setOptions({ layoutName: this.layoutName = list.join('-') })
      };

Can you tell me what I need to do to meet the guidelines in order to initiate a pull request?

Thank you.

**Comment by hodgef** [comment]
Hey @dkc-1379,

I'm sorry, we're no longer accepting new layouts to the codebase. Please check out the notice here:
https://github.com/simple-keyboard/simple-keyboard-layouts?tab=readme-ov-file#-contributing

Thanks
