### ISSUE TITLE
Unable to dynamically import individual layouts in node.js

### ISSUE THREAD

**Issue by slangreck** [simple-keyboard/simple-keyboard-layouts#2303]
**Simple-keyboard version**
3.3.98

**Describe the bug**
When I try to import a layout dynamically, like this:

``` JS
const { default: imported } = await import(`simple-keyboard-layouts/build/layouts/${configuredLayout}.js`);
```

I get the error "Unexpected token 'export'".

This can be fixed by adding `"type": "module"` to the package.json of the simple-keyboard-layouts package. Or is there another way to dynamically import layouts that I should be using?

**Comment by hodgef** [comment]
Hey @slangreck, I've added the commonjs layouts in version 3.4.0
https://github.com/simple-keyboard/simple-keyboard-layouts/tree/master/build/commonjs/layouts

Regards,
Francisco Hodge

**Comment by slangreck** [comment]
Thanks so much!
