### ISSUE TITLE
Support for Polish keyboard layout

### ISSUE THREAD

**Issue by maciej-sielski** [simple-keyboard/simple-keyboard-layouts#490]
Hi,
I'd like to see support for Polish keyboard layout. My proposal below. I'm just not sure about Polish-specific letters (should they be on top or bottom). Please adjust so that it could be consistent with other languages (e.g. czech)

```
export const polish = {
  default: [
    '` 1 2 3 4 5 6 7 8 9 0 - = {bksp}',
    '{tab} q w e r t y u i o p [ ] \\',
    '{lock} a s d f g h j k l ; \' {enter}',
    '{shift} z x c v b n m , . / {shift}',
    '.com @ {space} ą ę ć ł ń ó ś ż ź'
  ],
  shift: [
    '~ ! @ # $ % ^ & * ( ) _ + {bksp}',
    '{tab} Q W E R T Y U I O P { } |',
    '{lock} A S D F G H J K L : " {enter}',
    '{shift} Z X C V B N M < > ? {shift}',
    '.com @ {space} Ą Ę Ć Ł Ń Ó Ś Ż Ź'
  ]
};

```

Thank you.

**Comment by hodgef** [comment]
Hey @maciej-sielski ,

If you can follow this guide ( https://github.com/simple-keyboard/simple-keyboard-layouts/wiki/Adding-a-Layout ) to submit this as a PR. It'd be very appreciated!

Thanks,
Francisco Hodge

**Comment by maciej-sielski** [comment]
@hodgef I'm sorry to be a bother, but after PR you've totally lost big polish letters except for "Ł".

**Comment by hodgef** [comment]
Hello @maciej-sielski, please refer to #522 for an explanation on why I removed the letters added after the space key.

Ultimately I took this as reference
https://gate2home.com/Polish-Keyboard

Feel free to respond in #522 if you have anything to add. That way we can keep the discussion in a single thread.

Thanks
