### ISSUE TITLE
empty area on keyboard 

### ISSUE THREAD

**Issue by bluelemonade** [simple-keyboard/simple-keyboard-layouts#500]
hi,

I used your amazing vuejs implementation in my last project. 

now I should have an area on the kexboard without buttons. the row with the space bar should only show the space bar, but not over the complete width. Could this be done?

**Comment by hodgef** [comment]
Hey @bluelemonade,

I would suggest using CSS to getting that done. Simple-keyboard has several options to [give classes to buttons](https://franciscohodge.com/projects/simple-keyboard/documentation/#buttonTheme), to [group buttons together](https://franciscohodge.com/projects/simple-keyboard/qa-use-cases/style-customize-group-of-buttons/), etc which should accommodate most layouts.

Here's an example of a layout adapted with CSS:
https://github.com/hodgef/simple-keyboard/issues/63

If you try it but come across some issues let me know.

Thanks,
Francisco Hodge
