### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by leymane86** [simple-keyboard/simple-keyboard-layouts#668]
Hello,

The demo for your keyboard looks really cool, but I can not get it to work on my local copy. 

I thought using the CDN version would be pretty simple to get working. When I put the html code into a file and open it in my browser, I get this error "Uncaught SyntaxError: Cannot use import statement outside a module" and nothing shows up in the browser. I think the error is because the CSS is being loaded as a module, but I am not sure.

**Comment by hodgef** [comment]
The CDN snippets shouldn't have any import statements, please follow the CDN usage instructions closely and let me know if you still have issues. Thanks!
