### ISSUE TITLE
how would it be in angular2?

### ISSUE THREAD

**Issue by ifyum** [simple-keyboard/simple-keyboard-layouts#774]
layout: {
    default: [
      " 1 2 3 4 5 6 7 8 9 0 {bksp}",
      
      "k {enter}",
         
    ],
    shift: [
      "~ ! @ # $ % ^ & * ( ) _ + {bksp}",
      "{tab} Q W E R T Y U I O P { } |",
      '{lock} A S D F G H J K L : " {enter}',
      "{shift} Z X C V B N M < > ? {shift}",
      ".com @ {space}"
    ]
  },

**Comment by hodgef** [comment]
Hello @ifyum, it should be the same - Thanks!
