### ISSUE TITLE
options to hide keys

### ISSUE THREAD

**Issue by Danieliverant** [simple-keyboard/simple-keyboard-layouts#790]
I want to use your layouts (to get updates through npm and support all of the languages) but I want to have the option to hide unnecessary keys, for example, the ".com". or "tab" or any other key that is not a letter/comma/dot/delete/enter/caps.
it is possible?

thanks in advance

**Comment by hodgef** [comment]
Hello @Danieliverant,

Sadly this is not an option at the moment. Like I discussed on https://github.com/hodgef/simple-keyboard/issues/803#issuecomment-728638173, I think simple-keyboard-layouts would need a major release to address many of its limitations. 

I will file this into the Enhancement projects so I can pick it up when I have more time.

Thanks,
Francisco Hodge

**Comment by hodgef** [comment]
Update: Now you're able to hide keys with the option [excludeFromLayout](https://hodgef.com/simple-keyboard/documentation/options/excludefromlayout/).

Regards,
Francisco Hodge
