### ISSUE TITLE
Support for CapsLock mappings

### ISSUE THREAD

**Issue by meta-space** [simple-keyboard/simple-keyboard-layouts#906]
Hi

I noticed that the Swiss-german keyboard layout ( http://ascii-table.com/keyboard.php/150G ) hasn't been implemented yet.
I was thinking about contributing it myself, but I fear that it might not be possible to fully implement it at the moment.

All layouts I've seen have the following data structure:

const layout = {
  default: [ ...  ],
  shift: [ ...  ]
};

Due to some oddities in the Swiss system, the Shift and Caps-Lock keymaps are not identical. Specifically if you want type capital ÖÜÄ, you can only do it using Caps-Lock. When you use Shift, it will type the French accents éèà.  Does simple-keyboard support this scenario? Ideally, I could provide a keyboard layout such as:

const layout = {
  default: [ ...  ],
  shift: [ ...  ],
  capslock: [... ],
};

If no capslock is provided in a layout, you could fallback to shift.

**Comment by hodgef** [comment]
Hey @meta-space, simple-keyboard [does support different actions for shift and caps-lock](https://hodgef.com/simple-keyboard/questions-answers/shift-caps-lock-behaving-same/).

However, I would prefer if the layouts in `simple-keyboard-layouts` have the same structure.

The reason for this is that any change in layout structure here can potentially break people's implementations, especially if they're using these layouts in a language switcher such as [this one](https://codesandbox.io/s/github/hodgef/simple-keyboard-layouts-languages-list-demo). Shift handling is not done in the library, it's something that every dev [handles in their `onChange` function](https://github.com/hodgef/simple-keyboard/blob/a2f405d7fd8465ece4da5ca0a4976cd10371f4f6/src/demo/BasicDemo.js#L45).

You are more than welcome to submit a "simplified" version of the Swiss-german layout though!

Regards,
Francisco Hodge

**Comment by meta-space** [comment]
I hadn't seen that demo. That's what I was looking for, thanks!
