### ISSUE TITLE
There is not a typescript version for this library

### ISSUE THREAD

**Issue by RGiorgio** [simple-keyboard/simple-keyboard-layouts#920]
Actually this library does not include a typescript version, importing the lib in a typescript project generates the following error message : 
`Could not find a declaration file for module 'simple-keyboard-layouts/build/layouts/english'. '[...]/simple-keyboard-layouts/build/layouts/english.js' implicitly has an 'any' type.`

Could you implement the typescript version ?

**Comment by hodgef** [comment]
Should now be fixed as of simple-keyboard-layouts 3.0.0. Feel free to update and give it a try.

Regards,
Francisco Hodge

**Comment by xinthose** [comment]
I just tried to use this package in Angular 12 and got the same error.  

`import layout from "simple-keyboard-layouts/build/layouts/spanish";`

yields:

> Could not find a declaration file for module 'simple-keyboard-layouts/build/layouts/spanish'. 'c:/Users/ADunsmoor/Documents/GitHub/PAL/8700/PAL8742/client/node_modules/simple-keyboard-layouts/build/layouts/spanish.js' implicitly has an 'any' type.

**Comment by hodgef** [comment]
Hey @xinthose, thanks for reporting this bug. This is now fixed as of simple-keyboard-layouts@3.1.0.

Closing this ticket to prevent any pings to OP, but please feel free to create another issue if you encounter an issue.

Thanks,
Francisco Hodge
